FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

RUN apt-get update && apt-get install -y \
    wget build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev \
    libncurses5-dev libgdbm-dev libnss3-dev \
    libffi-dev curl liblzma-dev tk-dev git cmake

RUN wget https://www.python.org/ftp/python/3.13.3/Python-3.13.3.tgz && \
    tar -xf Python-3.13.3.tgz && \
    cd Python-3.13.3 && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make altinstall && \
    cd .. && \
    rm -rf Python-3.13.3 Python-3.13.3.tgz

RUN ln -sf /usr/local/bin/python3.13 /usr/local/bin/python3 && \
    ln -sf /usr/local/bin/pip3.13 /usr/local/bin/pip3

USER vscode
WORKDIR /workspaces/${localWorkspaceFolderBasename}